#!/usr/bin/php -q
<?php
if (is_dir($vendor = __DIR__ . '/vendor')) {
    require($vendor . '/autoload.php');
} elseif (is_dir($vendor = __DIR__ . '/../../../vendor')) {
    require($vendor . '/autoload.php');
} else {
    die(
        'You must set up the project dependencies, run the following commands:'.PHP_EOL.
        'curl -s http://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install'.PHP_EOL
    );
}

$options = getopt('f:',array(
    'debug',
    'excmd::',
    'fields::',
    'format::',
    'version',
));

if(!isset($options['debug'])) {
    error_reporting(0);
}

if(isset($options['version'])) {
    echo <<<'EOF'
Version: 0.2

Exuberant Ctags compatiable PHP enhancement, Copyright (C) 2012 Techlive Zheng
Addresses: <techlivezheng@gmail.com>, https://github.com/techlivezheng/phpctags

EOF;
    exit;
}

$file = realpath(array_pop($argv));

if(!isset($options['excmd']))
    $options['excmd'] = 'pattern';
if(!isset($options['format']))
    $options['format'] = 2;
if(!isset($options['fields'])) {
    $options['fields'] = array('n', 'k','s', 'a');
} else {
    $options['fields'] = str_split($options['fields']);
}

$ctags = new PHPCtags();
$ctags->export($file, $options);
