#!/usr/bin/php -q
<?php

if (is_dir($vendor = __DIR__ . '/vendor')) {
    require($vendor . '/autoload.php');
} elseif (is_dir($vendor = __DIR__ . '/../../../vendor')) {
    require($vendor . '/autoload.php');
} else {
    die(
        'You must set up the project dependencies, run the following commands:'.PHP_EOL.
        'curl -s http://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install'.PHP_EOL
    );
}

$options = getopt('f:',array('version'));

if(isset($options['version'])) {
    echo <<<'EOF'
Exuberant Ctags compatiable PHP enhancement, Copyright (C) 2012 Techlive Zheng
Addresses: <techlivezheng@gmail.com>, https://github.com/techlivezheng/phpctags
EOF;
    exit;
}

$file = realpath(array_pop($argv));

$ctags = new PHPCtags($file);
$ctags->export();
